### ISSUE TITLE
Random symmetrical matrices for solving generalized eigenvalue problem

### ISSUE THREAD

**Issue by DanielMartensson** [optimatika/ojAlgo#254]
Hi!

There is nothing wrong with this code. But I have a request.

```
        // A*V = B*D*V - Find D and V
	static public void eig(double A[][], double B[][], double D[], double V[][], int rows) {
		
		// Create eigA and eigB from symmetrical A and B
		Primitive64Matrix eigA = Primitive64Matrix.FACTORY.rows(A);
		Primitive64Matrix eigB = Primitive64Matrix.FACTORY.rows(B);
		
		// Perform [A][V] = [B][V][D]
		Eigenvalue.Generalised<Double> eig = Eigenvalue.PRIMITIVE.makeGeneralised(eigA);
		boolean success = eig.decompose(eigA, eigB);
		if(success == false)
			logger.error("Could not perform eigenvalue decomposition!");
		MatrixStore<Double> Deig = eig.getD();
		MatrixStore<Double> Veig = eig.getV();
		
		// Copy over to D, V
		for(int i = 0; i < rows; i++) {
			D[i] = Deig.get(i, i);
			for(int j = 0; j < rows; j++) {
				V[i][j] = Veig.get(i, j);
			}
		}	
	}
```
**Request:**

Can OjAlgo have random symmetrical matrices when solving generalized eigenvalue decomposition? Right now, A and B are symmetrical, but not all values are positive. Some of them are negative.

This is equivalent with MATLAB command:
```
[V, D] = eig(A, B)
```

Right now I solving this as:

```
                // Create symmetrical eigA and eigB
		Primitive64Matrix eigA = Primitive64Matrix.FACTORY.rows(A);
		Primitive64Matrix eigB = Primitive64Matrix.FACTORY.rows(B);
		
		// Find inverse of eigB - Or pseudo inverse if B is singular
		eigB = eigB.invert();
		
		// Multiply eigB*eigA
		Primitive64Matrix data = eigB.multiply(eigA);
		
		// Perform eigendecomposition
		Eigenvalue<Double> eig = Eigenvalue.PRIMITIVE.make(data,false);
		boolean success = eig.decompose(data);
```

But sometimes the eigenvalues and eigenvectors are complex. Some times not.
They should not be complex if I'm using the MATLAB routine.

**Comment by apete** [comment]
I don't understand what you're asking?

**Comment by DanielMartensson** [comment]
> I don't understand what you're asking?

Ska vi ta det på Svenska då?

I tried to use A and B as two random symmetrical matrices and that does not work. According to NetLib https://www.netlib.org/lapack/lug/node54.html
"A and B are real symmetric or complex Hermitian and B is positive definite".

In this case, B is not positive definite at all. Both A and B in my case are random symmetrical, which means they have both real negative and real positive values. 

OjAlgo cannot compute this in this current setup. MATLAB can do this. But I'm building image recognition library in pure Java. The library can do image recognition with small amount of training data. I will upload it later on my git if you want to have a look at it. But first things first. The eigenvalues need to be the same as MATLAB shows. That's why I'm asking this request if it's possible to add this feature into OjAlgo?

OjAlgo is the only java library that can solve generalized eigenvalue problem.

**Comment by apete** [comment]
> A and B are real symmetric or complex Hermitian and B is positive definite

That is currently the only implemented case.

Adding support for generalized nonsymmetric eigenproblems is no small task. I have absolutely nothing against ojAlgo gaining support for this, but you have to build it (PR:s are welcome).

**Comment by DanielMartensson** [comment]
> > A and B are real symmetric or complex Hermitian and B is positive definite
> 
> That is currently the only implemented case.
> 
> Adding support for generalized nonsymmetric eigenproblems is no small task. I have absolutely nothing against ojAlgo gaining support for this, but you have to build it (PR:s are welcome).

Detta kommer jag aldrig att klara utav. Mörk linjär algebra är inte min starkaste sida.
Annars så delar jag med mig utav mitt projekt jag har byggt. Bildigenkänning.

Jag har lyckats lösa problemet igenom att få Java tala med GNU Octave. 
https://github.com/DanielMartensson/jFaces---Image-classification-in-Java-

**Comment by DanielMartensson** [comment]
> > A and B are real symmetric or complex Hermitian and B is positive definite
> 
> That is currently the only implemented case.
> 
> Adding support for generalized nonsymmetric eigenproblems is no small task. I have absolutely nothing against ojAlgo gaining support for this, but you have to build it (PR:s are welcome).

Hi! I refresh my memory about positive definitive matrices and It seems that I'm using positive definitive matrices.

I post this output. It seems that there is a bug or something.

```
true
true
0.15692957189201065
0.18282868629930665
0.16851973340339388
0.18158570915159217
0.15898640337487352
0.17069635133768984
0.26522490484785644
0.09883842452993255
0.16048318711084694
0.1895967032097155
0.0347743056544924
0.10312014271361161
0.20933573621320636
0.3437122790686001
0.056087053790552496
0.09569019352241044
0.3606869569935913
0.1441773351074949
0.24714682143524214
0.20910638433418022
0.029684137351156638
0.11083620686991251
0.1242232603188754
0.2761772233688698
0.24528194317866325
0.1681054370307315
0.06776950899799183
0.18280253337791288
0.08898086778104158
0.24306837607458992
0.19539305653107614
0.15964339032840708
0.10653414790214974
0.2969872759709867
0.14264273928914956
0.1480174313925055
0.19467943534521487
0.20089816094613946
0.2816717093382307
0.2151928814986337
0.18477290862678042
0.2262613814979591
0.16026737804279467
0.06585005011161903
0.10180450675465884
0.2868257539366922
0.2359837128517117
0.14719916333095479
0.1674047499323825
0.06188394691422063
0.049058982514034705
0.08824524464636557
0.31531357361415946
0.03084946343620295
0.09856190344663648
0.21097050487736463
0.18076135461340376
0.16627992168105812
0.07555348466619266
0.17402512233976877
0.10723967896136685
0.05564501267544336
0.05009078327642204
0.18834525322231285
0.3404225768705794
0.17389990146879952
0.21625982711394384
0.21348948318077196
0.12085202311565066
0.32062016357553136
0.08544257647606432
0.040226835611386805
0.3806483555377193
0.2965659078459896
0.08526124200188287
0.29321885428041705
0.1260789498140659
0.1577792172530638
0.14626291340740144
0.23137596163434976
0.18433578509048354
0.22776975546879089
0.18948342891553882
0.3351067506283532
0.21458697346808492
0.05845333892670527
0.10452325787264519
0.19571165243549601
0.10634098700031136
0.3504716007782898
0.09884142969544975
0.1144664486032743
0.1291328878177484
0.07772201619645137
0.15878523658543883
0.39361399498041283
0.18120413535868315
0.36259026341403366
0.08015575944163884
0.22873915408538306
0.2629579599136116
0.2312814390320533
0.2681432453566034
0.20816443536990442
0.4507675964518195
0.3454560560086785
0.11692252160133276
0.05370693838978848
0.13311638426430725
0.26240415334232176
0.12746734298538978
0.09360906897766384
0.23783875458577217
0.24037819236379895
0.18713965279176736
0.10671951802738142
0.21760742864096883
0.1548681212645193
0.12202925386455574
0.23215141601954534
0.30308952014245616
0.38961487815742857
0.13320019206485345
0.2937047306451062
0.24628442650875676
0.24412752549636968
0.33470443474415335
0.10517961225111787
0.2591151012534215
0.18991955409605893
0.11773225877755442
0.14917174093534447
0.11864998013670283
0.032007507162878535
0.16490238414817554
0.0702084328326473
0.36147989596152297
0.19088168048405874
0.11492159596259285
0.058614929608466496
0.22908010033682075
0.19095422588081426
0.18200775185025628
0.1439767723675271
0.14920272560218126
0.11021125197187694
0.10077543588473066
0.14230170165999415
0.16171164113946637
0.0245553044906619
Positive definitive:
5.656248173236595E8
1.1643797331650946E9
[main] ERROR se.danielmartensson.fisherfaces.matlab.ojalgo.OjAlgoEig - Could not perform eigenvalue decomposition!
true
true
Exception in thread "main" java.lang.NullPointerException
	at se.danielmartensson.fisherfaces.matlab.ojalgo.OjAlgoEig.eig(OjAlgoEig.java:48)
	at se.danielmartensson.fisherfaces.Lda.scatters(Lda.java:94)
	at se.danielmartensson.fisherfaces.Lda.lda(Lda.java:53)
	at se.danielmartensson.fisherfaces.Fisherfaces.buildModel(Fisherfaces.java:62)
	at se.danielmartensson.fisherfaces.Fisherfaces.train(Fisherfaces.java:26)
	at se.danielmartensson.fisherfaces.Prediction.predictProcedure(Prediction.java:54)
	at se.danielmartensson.fisherfaces.Prediction.predictionRandom(Prediction.java:17)
	at se.danielmartensson.Main.main(Main.java:27)
```

Code:
```
public class OjAlgoEig {

	static Logger logger = LoggerFactory.getLogger(OjAlgoEig.class);

	// A*V = B*D*V - Find D and V - Will not work for current OjAlgo version
	static public void eig(double A[][], double B[][], double D[], double V[][], int rows) {

		// Create eigA and eigB from ->random<- symmetrical A and B
		Primitive64Matrix eigA = Primitive64Matrix.FACTORY.rows(A);
		Primitive64Matrix eigB = Primitive64Matrix.FACTORY.rows(B);
		
		// Check if it's symmetric
		System.out.println(eigA.isSymmetric()); // True
		System.out.println(eigA.isSymmetric()); // True
		
		// Check if it's positive definitive
		Primitive64Matrix z = Primitive64Matrix.FACTORY.makeFilled(rows, 1, new Weibull(5, 2));
		for(int i = 0; i < rows; i++) {
			System.out.println(z.get(i));
		}
		System.out.println("Positive definitive:");
		System.out.println(z.transpose().multiply(eigA).multiply(z).get(0, 0)); // z^T*eigA*z
		System.out.println(z.transpose().multiply(eigB).multiply(z).get(0, 0)); // z^T*eigA*z

		// Perform [A][V] = [B][V][D]
		Eigenvalue.Generalised<Double> eig = Eigenvalue.PRIMITIVE.makeGeneralised(eigA, Generalisation.A_B);
		boolean success = eig.computeValuesOnly(eigA, eigB);
		if (success == false)
			logger.error("Could not perform eigenvalue decomposition!");
		MatrixStore<Double> Deig = eig.getD();
		MatrixStore<Double> Veig = eig.getV();
		
		System.out.println(Deig == null);
		System.out.println(Veig == null);

		// Copy over to D, V
		for (int i = 0; i < rows; i++) {
			D[i] = Deig.get(i, i);
			for (int j = 0; j < rows; j++) {
				V[i][j] = Veig.get(i, j);
			}
		}
	}
}
```

Can you reopen the question?

**Comment by apete** [comment]
If you can create a self contained, directly executable test case that clearly demonstrates the problem then open a new issue for that problem.
