### ISSUE TITLE
String too long

### ISSUE THREAD

**Issue by vogt31337** [optimatika/ojAlgo#3]
Hi,

in the two test files:
org.ojalgo.opsimisation.convex.ConvexProblems.java (Line 935)
org.ojalgo.opsimisation.convex.QuadraticProblems.java (Line 141)

there's a Stringbuilder qs, which holds around 65k elements. 
Java is complaining that this is too much (even Netbeans warns me because it could crash).

Maybe it's possible to split these up in multiple definitions and concat them later?

Greetings

**Comment by optimatika** [comment]
I never had a problem and eclipse doesn't complain/warn about anything. Where/how do you get a "complaint from Java"?

It is a very long string, and the use of StringBuilder is pointless. This test case is constructed (copied) from code sent in to show a problem.

**Comment by vogt31337** [comment]
I got the complaint when running the provided tests:

testP20120507(org.ojalgo.optimisation.convex.ConvexProblems)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.RuntimeException: Uncompilable source code - constant string too long
	at org.ojalgo.optimisation.convex.ConvexProblems.testP20120507(ConvexProblems.java:935)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at junit.framework.TestSuite.runTest(TestSuite.java:255)
	at junit.framework.TestSuite.run(TestSuite.java:250)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Tests in error: 
  testP20120507(org.ojalgo.optimisation.convex.ConvexProblems): Uncompilable source code - constant string too long

**Comment by optimatika** [comment]
Removed that test case, and created and issue to try to bring it back in some from.
