### ISSUE TITLE
NegativeArraySizeException while using ExpressionBasedModel.minimise()

### ISSUE THREAD

**Issue by inzemamul-haque** [optimatika/ojAlgo#317]
I have defined the function createAndSolveLP which takes a list of nodes and a list of edges and then creates and solves an LP. There are 7625 nodes and 20744 edges. For each edge there are two variables and for each node there is a constraint. So there are 41488 variables and 7625 constraints. After adding variables and constraints to the model, when I call ExpressionBasedModel.minimise(), I get the NegativeArraySizeException. Error trace is given below. Please help.

java.lang.NegativeArraySizeException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:678)
	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:722)
	at java.base/java.util.concurrent.ForkJoinPool.invoke(ForkJoinPool.java:2432)
	at org.ojalgo.optimisation.integer.IntegerSolver.solve(IntegerSolver.java:401)
	at org.ojalgo.optimisation.ExpressionsBasedModel$Intermediate.solve(ExpressionsBasedModel.java:265)
	at org.ojalgo.optimisation.ExpressionsBasedModel.optimise(ExpressionsBasedModel.java:1451)
	at org.ojalgo.optimisation.ExpressionsBasedModel.minimise(ExpressionsBasedModel.java:1060)
	at ojAlgoTrial.newOjAlgoTest.createAndSolveLP(newOjAlgoTest.java:228)
	at ojAlgoTrial.newOjAlgoTest.main(newOjAlgoTest.java:62)
Caused by: java.lang.NegativeArraySizeException: -2102153036
	at org.ojalgo.array.Primitive64Array.<init>(Primitive64Array.java:112)
	at org.ojalgo.matrix.store.Primitive64Store.<init>(Primitive64Store.java:402)
	at org.ojalgo.matrix.store.Primitive64Store$1.make(Primitive64Store.java:167)
	at org.ojalgo.matrix.store.Primitive64Store$1.make(Primitive64Store.java:64)
	at org.ojalgo.structure.Factory2D.makeZero(Factory2D.java:105)
	at org.ojalgo.optimisation.linear.SimplexTableau$DenseTableau.<init>(SimplexTableau.java:63)
	at org.ojalgo.optimisation.linear.SimplexTableau.make(SimplexTableau.java:899)
	at org.ojalgo.optimisation.linear.PrimalSimplex.build(PrimalSimplex.java:147)
	at org.ojalgo.optimisation.linear.LinearSolver$ModelIntegration.build(LinearSolver.java:165)
	at org.ojalgo.optimisation.linear.LinearSolver$ModelIntegration.build(LinearSolver.java:154)
	at org.ojalgo.optimisation.ExpressionsBasedModel$Intermediate.getSolver(ExpressionsBasedModel.java:321)
	at org.ojalgo.optimisation.ExpressionsBasedModel$Intermediate.solve(ExpressionsBasedModel.java:261)
	at org.ojalgo.optimisation.integer.IntegerSolver.compute(IntegerSolver.java:454)
	at org.ojalgo.optimisation.integer.IntegerSolver$BranchAndBoundNodeTask.compute(IntegerSolver.java:135)
	at org.ojalgo.optimisation.integer.IntegerSolver$BranchAndBoundNodeTask.compute(IntegerSolver.java:87)
	at java.base/java.util.concurrent.RecursiveTask.exec(RecursiveTask.java:95)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by apete** [comment]
That's a large MIP model, and looks like an integer overflow problem when creating some matrix. You'll have to do a bit more debugging and/or provide some sort of test that I can run. How many of the 41488 variables are integer variables? It could be that this problem is simply too big for ojAlgo.

**Comment by inzemamul-haque** [comment]
Will need to work on creating a test.  All the variables are integer variables.

**Comment by apete** [comment]
I'm interested in seeing where/why that integer overflow occurs. When that problem is fixed you have a MIP model with 41488 integer variables. Either the presolver can do wonders and reduce the problem size significantly or I believe this is too much for ojAlgo.

The test case should be easy to construct. The problem seems to be related to instantiating a solver from a very large model. The actual model parameters and solution probably doesn't matter.
