### ISSUE TITLE
Tests randomly fail

### ISSUE THREAD

**Issue by flaghacker** [optimatika/ojAlgo#68]
I can't build the library right now, `RandomNumberTest` or `SingularValueTest` sometimes fail, with a different error each time.

<details><summary>Example 1</summary>

```
Failed tests:   testGamma(org.ojalgo.random.RandomNumberTest): Sample mean was 1.028919709412292, distribution mean was 1.0. expected:<1.028919709412292> but was:<1.0>

Tests run: 209, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.268 s
[INFO] Finished at: 2018-03-12T08:56:40+01:00
[INFO] Final Memory: 28M/603M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ojalgo: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Karel\Desktop\Build ojalgo\ojAlgo\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ojalgo: There are test failures.

Please refer to C:\Users\Karel\Desktop\Build ojalgo\ojAlgo\target\surefire-reports for the individual test results.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to C:\Users\Karel\Desktop\Build ojalgo\ojAlgo\target\surefire-reports for the individual test results.
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:83)
    at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary (SurefirePlugin.java:176)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:150)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:650)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:586)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
</details>

<details><summary>Example 2</summary>

```
Failed tests:   testSampledMean(org.ojalgo.random.RandomNumberTest): Normal expected:<0.0> but was:<-0.11502726781557226>

Tests run: 209, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.163 s
[INFO] Finished at: 2018-03-12T09:02:31+01:00
[INFO] Final Memory: 27M/512M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ojalgo: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Karel\Desktop\Build ojalgo\ojAlgo\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ojalgo: There are test failures.

Please refer to C:\Users\Karel\Desktop\Build ojalgo\ojAlgo\target\surefire-reports for the individual test results.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to C:\Users\Karel\Desktop\Build ojalgo\ojAlgo\target\surefire-reports for the individual test results.
    at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution (SurefireHelper.java:83)
    at org.apache.maven.plugin.surefire.SurefirePlugin.writeSummary (SurefirePlugin.java:176)
    at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary (SurefirePlugin.java:150)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked (AbstractSurefireMojo.java:650)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute (AbstractSurefireMojo.java:586)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
</details>

<details><summary>Example 3</summary>

```
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.437 sec <<< FAILURE!
testRandomSquareCase(org.ojalgo.matrix.decomposition.SingularValueTest)  Time elapsed: 0.172 sec  <<< FAILURE!
junit.framework.AssertionFailedError: SingularValue<N> expected:<org.ojalgo.matrix.store.ComplexDenseStore < 8 x 8 >
{ { (2.499760451917726 + 0.0i), (3.527743685995949 + 0.0i),     (4.662817999466646 + 0.0i),     (1.72385992683264 + 0.0i),      (0.5016446420697318 + 0.0i),    (0.6492300247497718 + 0.0i),    (0.8649010160270714 + 0.0i),    (5.284843046949209 + 0.0i) },
{ (4.720300689611867 + 0.0i),   (5.818099693236926 + 0.0i),     (5.233818146710731 + 0.0i),     (5.855018809932886 + 0.0i),     (3.115252481075881 + 0.0i),     (0.4322693249379133 + 0.0i),    (2.427494584928736 + 0.0i),     (4.372492677517891 + 0.0i) },
{ (0.5429143524013447 + 0.0i),  (5.854762978372245 + 0.0i),     (0.5871183803917388 + 0.0i),    (1.543608260272446 + 0.0i),     (5.615910892380532 + 0.0i),     (2.592839254088847 + 0.0i),     (5.856072690786387 + 0.0i),     (3.912850406439847 + 0.0i) },
{ (3.785903695647925 + 0.0i),   (3.102257911284102 + 0.0i),     (4.5991272580882 + 0.0i),       (3.169646493223153 + 0.0i),     (2.737985087892073 + 0.0i),     (5.829978083465515 + 0.0i),     (2.876076869243659 + 0.0i),     (0.6238520547358823 + 0.0i) },
{ (0.4235461382009782 + 0.0i),  (4.844381059710229 + 0.0i),     (4.424326818716773 + 0.0i),     (1.683217622674778 + 0.0i),     (2.693340688760603 + 0.0i),     (4.325228958715321 + 0.0i),     (0.4303888604902877 + 0.0i),    (1.117834472065064 + 0.0i) },
{ (1.246664026040171 + 0.0i),   (4.241241136192584 + 0.0i),     (2.81535004790768 + 0.0i),      (1.127494617111985 + 0.0i),     (5.686731885514387 + 0.0i),     (2.029373262439739 + 0.0i),     (0.5788577104332049 + 0.0i),    (1.302404970210216 + 0.0i) },
{ (2.770725618528353 + 0.0i),   (3.960398059304565 + 0.0i),     (0.4243580427698515 + 0.0i),    (0.9258721746506664 + 0.0i),    (2.570699488516595 + 0.0i),     (0.4365187611937791 + 0.0i),    (0.9853339018619005 + 0.0i),    (5.287773532294669 + 0.0i) },
{ (5.701957359834497 + 0.0i),   (4.053991345544266 + 0.0i),     (5.609892913977285 + 0.0i),     (5.848511729499727 + 0.0i),     (3.519923282955612 + 0.0i),     (0.4363689725862376 + 0.0i),    (2.117924047270422 + 0.0i),     (2.944719800520183 + 0.0i) } }> but was:<org.ojalgo.matrix.decomposition.SingularValueDecomposition$Complex@4563e9ab>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at org.ojalgo.TestUtils.assertEquals(TestUtils.java:181)
        at org.ojalgo.matrix.decomposition.SingularValueTest.doTestTypes(SingularValueTest.java:337)
        at org.ojalgo.matrix.decomposition.SingularValueTest.testRandomSquareCase(SingularValueTest.java:205)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

And then RandomNumberTest got stuck and I had to terminate the tests.
</details>

**Comment by apete** [comment]
I've had the bad habit of writing tests with randomly generated input. Most of these tests have already been fixed or turned off. There are a few remaining tests, that sometimes fail. Until they're fixed, I've still decided that I loose more by turning them off.

This will be fixed eventually, but not today...

**Comment by apete** [comment]
Several things have been done towards solving this issue. Could you "evaluate" to which extent this issue is solved? Unstable tests can be tagged as such `@Tag("unstable")`. If you think the tests are now in a reasonable state then please close this issue.

**Comment by flaghacker** [comment]
I ran the tests a couple of times, everything seems to be stable, in the sense that right now two tests are consistently failing:

<details><summary>testFrom(org.ojalgo.type.TimeIndexTest)</summary>
OffsetDateTime expected:<2018-03-28T21:58:03.516+02:00> but was:<2018-03-28T20:58:03.516+01:00>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at org.ojalgo.TestUtils.assertEquals(TestUtils.java:322)
        at org.ojalgo.type.TimeIndexTest.doTestFrom(TimeIndexTest.java:23)
        at org.ojalgo.type.TimeIndexTest.testFrom(TimeIndexTest.java:84)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</details>

<details><summary>testRandomSquareCase(org.ojalgo.matrix.decomposition.SingularValueTest)</summary>
testRandomSquareCase(org.ojalgo.matrix.decomposition.SingularValueTest)  Time elapsed: 0.141 sec  <<< FAILURE!
junit.framework.AssertionFailedError: SingularValue<N> expected:<org.ojalgo.matrix.store.ComplexDenseStore < 8 x 8 >
{ { (0.4747755614025277 + 0.0i),        (5.606424707814861 + 0.0i),     (1.927184021344309 + 0.0i), (4.164188964460805 + 0.0i), (1.78581357071015 + 0.0i),      (1.904121027865504 + 0.0i),     (0.4235924651574394 + 0.0i),    (3.47884733234581 + 0.0i) },
{ (5.338112803336726 + 0.0i),   (3.214669934121365 + 0.0i),     (3.981948316032671 + 0.0i),     (1.089164161721646 + 0.0i),     (2.719288307740166 + 0.0i),     (2.855233864104378 + 0.0i),     (0.7722523393390333 + 0.0i),    (4.513004165729316 + 0.0i) },
{ (5.815945106966388 + 0.0i),   (0.4283084594906597 + 0.0i),    (3.753927611975806 + 0.0i),     (4.429772290952119 + 0.0i),     (3.078586739872637 + 0.0i),     (4.476409596792799 + 0.0i),     (0.482739249260363 + 0.0i),     (4.451924402018181 + 0.0i) },
{ (5.033267298701826 + 0.0i),   (4.762163268012076 + 0.0i),     (5.21824112502278 + 0.0i),      (2.599125218247372 + 0.0i),     (5.364176510816375 + 0.0i),     (5.246014205349312 + 0.0i),     (5.761909366424209 + 0.0i),     (1.066557322924802 + 0.0i) },
{ (4.176354727219265 + 0.0i),   (5.398926141708136 + 0.0i),     (4.110488604212421 + 0.0i),     (0.6451205231409931 + 0.0i),    (4.147780303069715 + 0.0i),     (1.195695304240844 + 0.0i),     (2.700701063925794 + 0.0i),     (5.829299484072552 + 0.0i) },
{ (5.859477616146252 + 0.0i),   (1.493967108826274 + 0.0i),     (2.021196787051021 + 0.0i),     (0.5002341353801181 + 0.0i),    (4.803511943690413 + 0.0i),     (1.981035044044798 + 0.0i),     (5.856185731040817 + 0.0i),     (4.191104289540152 + 0.0i) },
{ (0.6068473714143154 + 0.0i),  (3.118175137105535 + 0.0i),     (5.427100325604305 + 0.0i),     (5.014535381335211 + 0.0i),     (0.5899576619443581 + 0.0i),    (3.080328289266443 + 0.0i),     (1.607850345137129 + 0.0i),     (2.024619717460832 + 0.0i) },
{ (0.4756186126243191 + 0.0i),  (3.281090068428452 + 0.0i),     (4.044351322795642 + 0.0i),     (5.228157802078139 + 0.0i),     (4.113563471194494 + 0.0i),     (0.4333257433975435 + 0.0i),    (5.834114062201081 + 0.0i),     (5.569803200670418 + 0.0i) } }> but was:<org.ojalgo.matrix.decomposition.SingularValueDecomposition$Complex@4563e9ab>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at org.ojalgo.TestUtils.assertEquals(TestUtils.java:181)
        at org.ojalgo.matrix.decomposition.SingularValueTest.doTestTypes(SingularValueTest.java:337)
        at org.ojalgo.matrix.decomposition.SingularValueTest.testRandomSquareCase(SingularValueTest.java:205)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:252)
        at junit.framework.TestSuite.run(TestSuite.java:247)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
</details>

I guess you already know about those since they're reliably reproducible?

**Comment by apete** [comment]
No, I did not know about that. There should be no failing tests. Have you pulled the latest changes?

The testFrom() test in TimeIndexTest started failing on this weekend when Europe switched to summer time, but that has been fixed.
